[package]
name = "ethers-reth"
version = "0.1.0"
edition = "2021"


[dependencies]
reth-tasks = { git = "https://github.com/paradigmxyz/reth", package = "reth-tasks", rev = "d5ea168" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc", rev = "d5ea168" }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-api", rev = "d5ea168" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-types", rev = "d5ea168" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", package = "reth-provider", rev = "d5ea168" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", package = "reth-transaction-pool", rev = "d5ea168" }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-network-api", rev = "d5ea168" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-primitives", rev = "d5ea168" }
reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db", rev = "d5ea168", features = ["test-utils"] }
reth-blockchain-tree = { git = "https://github.com/paradigmxyz/reth", package = "reth-blockchain-tree", rev = "d5ea168" }
reth-beacon-consensus = { git = "https://github.com/paradigmxyz/reth", package = "reth-beacon-consensus", rev = "d5ea168" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", package = "reth-revm", rev = "d5ea168" }
reth-interfaces = { git = "https://github.com/paradigmxyz/reth", package = "reth-interfaces", rev = "d5ea168", features = ["test-utils"] }
reth-stages = { git = "https://github.com/paradigmxyz/reth", package = "reth-stages", rev = "d5ea168", features = ["test-utils"] }
reth-trie = { git = "https://github.com/paradigmxyz/reth", package = "reth-trie", rev = "d5ea168" }
reth-eth-wire = { git = "https://github.com/paradigmxyz/reth", package = "reth-eth-wire", rev = "d5ea168" }

# ethers
ethers = { version = "2.0.8", default-features = false, features = ["ipc", "ws", "rustls", "ethers-solc"] }

# Async
tokio = { version = "1.28.2", features = ["full"] }
async-trait = "0.1.68"

# Misc
eyre = "0.6.8"
thiserror = "1.0.40"

jsonrpsee = { version = "0.18", features = ["server", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serial_test = "2.0.0"

[patch.crates-io]
# patched for quantity U256 responses <https://github.com/recmo/uint/issues/224>
revm-primitives = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }

[dev-dependencies]
pretty_assertions = "1.4.0"

